servers:
  - name: server1
    host: 192.x.x.x


  - name: server2
    host: 192.x.x.x
 

  - name: server3
    host: 192.x.x.x



email:
  sender: "example@email.com"
  password: "passwordhere"
  recipient: "email@recipient.com"
  smtp_server: "smtp.mail.service.com"
  smtp_port: 

